/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yumxpress.gui;

import java.awt.Image;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Map;
import java.util.Set;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import yumxpress.dao.ProductDAO;
import yumxpress.pojo.ProductPojo;
import yumxpress.utill.OwnerProfile;

/**
 *
 * @author JASRAJ
 */
public class ViewFoodFrame extends javax.swing.JFrame {

    /**
     * Creates new form ViewFoodFrame
     */
    private Map<String,ProductPojo>productDetails;
    public ViewFoodFrame() {
        initComponents();
       this.setLocationRelativeTo(null);
       this.OwnerProfileLbl.setText("Hello "+OwnerProfile.getOwnerName());
       loadProductDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        LblUser = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblSellerOption = new javax.swing.JLabel();
        lblFoodName = new javax.swing.JLabel();
        jCBSelectFood = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtProductPrice = new javax.swing.JTextField();
        lblFoodImage = new javax.swing.JLabel();
        BtnAddFood = new javax.swing.JButton();
        BtnAddStaff = new javax.swing.JButton();
        BtnViewStaff = new javax.swing.JButton();
        BtnOrderList = new javax.swing.JButton();
        OwnerProfileLbl = new javax.swing.JLabel();
        BtnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(129, 124, 178));

        LblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yumxpress/icons/user.png"))); // NOI18N

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setForeground(new java.awt.Color(129, 124, 178));

        lblSellerOption.setFont(new java.awt.Font("Times New Roman", 1, 56)); // NOI18N
        lblSellerOption.setForeground(new java.awt.Color(129, 124, 178));
        lblSellerOption.setText("View Food");

        lblFoodName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFoodName.setForeground(new java.awt.Color(129, 124, 178));
        lblFoodName.setText("Select Food Name ");

        jCBSelectFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBSelectFoodActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(129, 124, 178));
        jLabel2.setText("Price");

        txtProductPrice.setEditable(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblFoodName)
                                .addComponent(lblSellerOption)
                                .addComponent(jCBSelectFood, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(lblFoodImage, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblSellerOption)
                .addGap(30, 30, 30)
                .addComponent(lblFoodName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBSelectFood, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(lblFoodImage, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(37, 37, 37))
        );

        BtnAddFood.setBackground(new java.awt.Color(229, 247, 166));
        BtnAddFood.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BtnAddFood.setText("AddFood");
        BtnAddFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddFoodActionPerformed(evt);
            }
        });

        BtnAddStaff.setBackground(new java.awt.Color(229, 247, 166));
        BtnAddStaff.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BtnAddStaff.setText("Add staff");
        BtnAddStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddStaffActionPerformed(evt);
            }
        });

        BtnViewStaff.setBackground(new java.awt.Color(229, 247, 166));
        BtnViewStaff.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BtnViewStaff.setText("View staff");
        BtnViewStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewStaffActionPerformed(evt);
            }
        });

        BtnOrderList.setBackground(new java.awt.Color(229, 247, 166));
        BtnOrderList.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BtnOrderList.setText("Order List");
        BtnOrderList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOrderListActionPerformed(evt);
            }
        });

        OwnerProfileLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        BtnBack.setBackground(new java.awt.Color(229, 247, 166));
        BtnBack.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BtnBack.setText("Back");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnAddStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnAddFood, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnViewStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnOrderList, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OwnerProfileLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(LblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(BtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)))))
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(LblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OwnerProfileLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnAddFood)
                .addGap(18, 18, 18)
                .addComponent(BtnAddStaff)
                .addGap(18, 18, 18)
                .addComponent(BtnViewStaff)
                .addGap(18, 18, 18)
                .addComponent(BtnOrderList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(BtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAddFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddFoodActionPerformed
        AddFoodFrame foodFrame=new AddFoodFrame();
        foodFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnAddFoodActionPerformed

    private void BtnOrderListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOrderListActionPerformed
        OrderListFrame listFrame=new OrderListFrame();
        listFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnOrderListActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
          SellerOptionFrame optionFrame=new SellerOptionFrame();
        optionFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnBackActionPerformed

    private void jCBSelectFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBSelectFoodActionPerformed
        String foodName=jCBSelectFood.getSelectedItem().toString();
        ProductPojo product = productDetails.get(foodName);
        Image img=product.getProductImage();
      img=img.getScaledInstance(lblFoodImage.getWidth(),lblFoodImage.getHeight(), Image.SCALE_SMOOTH);
      ImageIcon icon=new ImageIcon(img);
      lblFoodImage.setIcon(icon);
      txtProductPrice.setText(product.getProductPrice()+"");
    }//GEN-LAST:event_jCBSelectFoodActionPerformed

    private void BtnAddStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddStaffActionPerformed

        AddDeliveryStaffFrame foodFrame=new AddDeliveryStaffFrame();
        foodFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnAddStaffActionPerformed

    private void BtnViewStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewStaffActionPerformed
        ViewDeliveryStaffFrame staffFrame = new ViewDeliveryStaffFrame();
        staffFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnViewStaffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewFoodFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewFoodFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewFoodFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewFoodFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewFoodFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddFood;
    private javax.swing.JButton BtnAddStaff;
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnOrderList;
    private javax.swing.JButton BtnViewStaff;
    private javax.swing.JLabel LblUser;
    private javax.swing.JLabel OwnerProfileLbl;
    private javax.swing.JComboBox<String> jCBSelectFood;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblFoodImage;
    private javax.swing.JLabel lblFoodName;
    private javax.swing.JLabel lblSellerOption;
    private javax.swing.JTextField txtProductPrice;
    // End of variables declaration//GEN-END:variables

    private void loadProductDetails() {
       try{
           productDetails=ProductDAO.getProductDetailsByCompanyId(OwnerProfile.getCompanyId());
           if(productDetails.isEmpty()){
               JOptionPane.showMessageDialog(null,"No food found for "+OwnerProfile.getCompanyId());
               return;
           }
           showProductNames();
       }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Exception in DB in ViewFoodFrame");
            ex.printStackTrace();
       }catch(IOException ex){
            JOptionPane.showMessageDialog(null,"Exception in DAO Image Processing in ViewFoodFrame");
            ex.printStackTrace();
       }
    }

    private void showProductNames() {
        Set<String> foodNames=productDetails.keySet();
       for(String foodName:foodNames){
           jCBSelectFood.addItem(foodName);
       }
    }
}
